### ISSUE TITLE
Skilifting PACT data

### ISSUE THREAD

**Issue by shihabdider** [mskilab-org/pgvdb#15]
This issue involves creating appropriate data inputs from PACT raw data for viewing on case-reports.

@kevinmhadi will post the list of plots we expect to be able to view on case-reports given the PACT data we currently have (e.g metadata, coverage, hetsnps, etc.)

@shihabdider will ready skilift for converting raw output files into JSONs/arrows and then pair with @kevinmhadi to convert the outputs and build a PACT case-reports instance.

**Comment by kevinmhadi** [comment]
So in summary: 

- Copy number track (total + allelic from the `facets__pact` column)
- SNV/Indel track + oncotable
- Possible QC, although I might need to provide custom Picard outputs for metrics
- Possible total and hetsnp coverage track (we would have to run our own pipeline for this on the bams we got)

Unfortunately, they didn't provide coverage, we can try running fragcounter + hetpileups and see if we can input those.

**Comment by shihabdider** [comment]
> So in summary:
> 
> * Copy number track (total + allelic from the `facets__pact` column)

We will need to convert these into gGraphs to skilift them.
 
> * SNV/Indel track + oncotable

For the first, we'd need to run SNVplicity (not sure if it's already compatible -- maybe @jrafailov can help). For oncotable (assuming you haven't already run it) we would need: annotations bcf, jabba/gGraph + karyograph, events, fusions (n.b all of these parameters are optional)
  
> * Possible QC, although I might need to provide custom Picard outputs for metrics
> * Possible total and hetsnp coverage track (we would have to run our own pipeline for this on the bams we got)

Amber (for hets) can be run on targeted panels (https://github.com/hartwigmedical/hmftools/blob/master/pipeline/README_TARGETED.md#step-1-run-cobalt-amber-sage--isofox-on-the-targeted-samples-in-wgts-mode), but this isn't implemented in our pipeline currently.

> Unfortunately, they didn't provide coverage, we can try running fragcounter + hetpileups and see if we can input those.

**Comment by shihabdider** [comment]
I ran AMBER (with the target bed) on the PACT bams. It ran, but the outputs are all empty:
`/gpfs/home/diders01/projects/Clinical_NYU/pact_amber_run/amber`. 

Here's a sample run: `/gpfs/scratch/diders01/pact_amber_run/work/e2/68e86399304b7886bf8372d9fb1530`

If you look at the `.command.log` it seems like there's a bam header mismatch? I'm using the rgfixed bams that I think you prepared @kevinmhadi . `.command.sh` shows the actual command that was run. 

Currently re-running with originals to see if there's any difference.

**Comment by kevinmhadi** [comment]
Hmm is this a "^chr" mismatch in the reference names? These were aligned to
an hg19 version with "chr":   

```bash
samtools view -H D1285B70-01DE-11EF-88A7-15EFA6892824-T.final.rgfixed.bam
@HD     VN:1.5  SO:coordinate   GO:none
@SQ     SN:chrM LN:16571
@SQ     SN:chr1 LN:249250621
@SQ     SN:chr2 LN:243199373
@SQ     SN:chr3 LN:198022430
```

**Comment by shihabdider** [comment]
OK seems like there's no alternative to changing the headers according to this issue: 
https://github.com/hartwigmedical/hmftools/issues/418#issuecomment-1599475799
I will go ahead and remove `chr` from all the ref names.

**Comment by kevinmhadi** [comment]
All the QC data + hetpileups sites.txt is in here now: 

"/gpfs/data/imielinskilab/projects/Clinical_NYU/db/pairs_pact_qc.rds"

Still awaiting:
Filtered events

**Comment by kevinmhadi** [comment]
Here's my code to parse picard QC into the pairs table - the QC inputs are in the melted samples table.. and then i merge based on the tumor_sample and normal_sample name. This is my custom workflow for the PACT data, but we can adapt for how we structure the WGS workflow. (i.e. if we never deal with the samples tables).

Can also deal with missing QC in a less strict way (don't fail if some, but not all QC outputs are present).

```R
ALIGNMENT_FIELD="alignment_summary_metrics"
INSERT_FIELD="insert_size_metrics"
WGS_FIELD="wgs_metrics"
ESTLC_FIELD="estimate_library_complexity"
PLATFORM="pact"
registerS3method("merge", "data.table", data.table::merge.data.table)
lst = samples %>% khtools::split_by("sample")
ix = 1:NROW(lst)
lst_metrics = lapply(ix, function(i) {
    x = lst[[i]]
    pathlst = list(
        wgs = x[[paste(WGS_FIELD, PLATFORM, sep = "__")]],
        alignment = x[[paste(ALIGNMENT_FIELD, PLATFORM, sep = "__")]],
        insert = x[[paste(INSERT_FIELD, PLATFORM, sep = "__")]],
        elc = x[[paste(ESTLC_FIELD, PLATFORM, sep = "__")]]
    )
    is_file_present = sapply(pathlst, file.exists)
    is_filelist_all_present = all(is_file_present)
    out = "missing"
    if (!is_filelist_all_present)
        return(out)
    outlst = lapply(pathlst, function(x) {
        out = data.table::fread(x) 
        if ("CATEGORY" == names(out)[1]) {
            out = out[CATEGORY == "PAIR"]
        }
        return(out)
    })
    metrics = do.call(cbind, unname(outlst))
    metrics$sample = x$sample
    out = metrics
    return(out)
})

presentMetrics = lst_metrics[sapply(lst_metrics, function(x) !identical(x, "missing"))] %>% data.table::rbindlist()
names(presentMetrics) = base::make.unique(names(presentMetrics))


pairs_clinical_pact_qc = merge(
  pairs_clinical,
  presentMetrics,
  by.x = "tumor_sample",
  by.y = "sample",
  all.x = TRUE
)


pairs_clinical_pact_qc = merge(
  pairs_clinical_pact_qc,
  presentMetrics[, .(sample, MEDIAN_COVERAGE)],
  by.x = "normal_sample",
  by.y = "sample",
  suffixes = c("__TUMOR", "__NORMAL"),
  all.x = TRUE
)

```
